---
title: "test_animation_play"
author: "Liam Dao"
date: "10/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages & Read in Data
```{r}
#Loading pre-installed libraries
library(tidyverse)
library(gganimate)
library(cowplot)
library(ggridges)
library(repr)
library(gifski)


#turning off warnings
options(warn=-1)

#setting plot width and height
options(repr.plot.width=15, repr.plot.height = 10)

#set directory
setwd("/Users/liamd/Documents/NFL Big Data Bowl/Data/")


##reading in non-tracking data

#includes play-by-play info on specific plays
df_plays <- read_csv("plays.csv",
                    col_types = cols())

#includes background info for players
df_players <- read_csv("players.csv",
                      col_types = cols())

head(df_plays)
head(df_players)

##Reading tracking data (needs to be done iteratively)

#weeks of NFL season
seasons <- seq(2018, 2020)

#blank dataframe to store tracking data
df_tracking <- data.frame()

#iterating through all weeks
for(s in seasons){
    
    #temperory dataframe used for reading season for given iteration
    df_tracking_temp <- read_csv(paste0("tracking",s,".csv"),
                                col_types = cols())
    
    #storing temporary dataframe in full season dataframe
    df_tracking <- bind_rows(df_tracking_temp, df_tracking)                            
    
}

head(df_tracking)

rm(df_tracking_temp)
```


## Cleaning  Data
```{r}
#Standardizing tracking data so its always in direction of punting team.
df_tracking <- df_tracking %>%
                mutate(x = ifelse(playDirection == "left", 120-x, x),
                       y = ifelse(playDirection == "left", 160/3 - y, y))

#Subset for punts
df_plays_punts <- df_plays %>% 
            filter(specialTeamsPlayType == 'Punt')

#Subset for Panthers
df_plays_panthers <- df_plays_punts %>% 
            filter(possessionTeam == 'CAR')

#Subset for Patriots
df_plays_patriots <- df_plays_punts %>% 
            filter(possessionTeam == 'NE')
```


## Animating Plays
```{r}
#loading command to make NFL field in ggplot (credit to Marschall Furman)
source('https://raw.githubusercontent.com/mlfurman3/gg_field/main/gg_field.R')

#picking the lowest offset play

example_play <- df_plays_panthers %>% 
                filter(playId == 511)# select CAR punt returned by Nyheim Hines

#merging tracking data to play
example_play <- inner_join(example_play,
                           df_tracking,
                           by = c("gameId" = "gameId",
                                  "playId" = "playId"))

#attributes used for plot. first is away, second is football, third is home.
cols_fill <- c("dodgerblue1", "#663300", "firebrick1")
cols_col <- c("#000000", "#663300", "#000000")
size_vals <- c(6, 4, 6)
shape_vals <- c(21, 16, 21)
plot_title <- example_play$playDescription[1]
nFrames <- max(example_play$frameId)

#plotting
anim <- ggplot() +


        #creating field underlay
        gg_field(yardmin = -2, yardmax = 122) +

        #filling forest green for behind back of endzone
        theme(panel.background = element_rect(fill = 'forestgreen',
                                              color = 'forestgreen'),
              panel.grid = element_blank()) +
    
    
     #setting size and color parameters
        scale_size_manual(values = size_vals, guide = FALSE) + 
        scale_shape_manual(values = shape_vals, guide = FALSE) +
        scale_fill_manual(values = cols_fill, guide = FALSE) + 
        scale_colour_manual(values = cols_col, guide = FALSE) +


        #adding players
        geom_point(data = example_play, aes(x = x,
                                          y = y, 
                                          shape = team,
                                          fill = team,
                                          group = nflId,
                                          size = team,
                                          colour = team), 
                 alpha = 0.7) +  

        #adding jersey numbers
        geom_text(data = example_play,
                  aes(x = x, y = y, label = jerseyNumber),
                  colour = "white", 
                vjust = 0.36, size = 3.5) + 


        #titling plot with play description
        labs(title = plot_title) +

        #setting animation parameters
        transition_time(frameId)  +
        ease_aes('linear') + 
        NULL 

animate(anim, width = 720, height = 440, fps = 10, nframe = nFrames,renderer=gifski_renderer("test.gif"))
```